FROM python:3.10-slim

WORKDIR /app

COPY services/requirements-dev.txt /app/services/requirements-dev.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl \
       unixodbc \
       unixodbc-dev \
       gcc \
       g++ \
    && pip install --no-cache-dir -r /app/services/requirements-dev.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY services /app/services

EXPOSE 8000

CMD ["uvicorn", "services.etl_engine.api.app:app", "--host", "0.0.0.0", "--port", "8000"]